"""Add read field to Message model

Revision ID: 130f3fe1c7ba
Revises: 
Create Date: 2025-04-25 12:47:37.332371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '130f3fe1c7ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_constraint('cart_item_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('cart_item_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('message_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('message_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['receiver_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['sender_id'], ['id'])

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint('order_item_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'order', ['order_id'], ['id'])

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('product_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['seller_id'], ['id'])

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('transaction_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'order', ['order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transaction_ibfk_1', 'order', ['order_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('product_ibfk_1', 'user', ['seller_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_item_ibfk_1', 'order', ['order_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('message_ibfk_1', 'user', ['sender_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('message_ibfk_2', 'user', ['receiver_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('read')

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cart_item_ibfk_2', 'product', ['product_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('cart_item_ibfk_1', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
